### ISSUE TITLE
xcode5下直接编译出错

### ISSUE THREAD

**Issue by skywalkerlw** [iAladdin/Weixin-Mac#1]
![screenshot](https://f.cloud.github.com/assets/2090084/897980/7d3fbc16-faff-11e2-8bd5-9b186f847fdf.png

**Comment by iAladdin** [comment]
请使用develop分支，master还没有合并

**Comment by powerbsd** [comment]
使用 Develop 分支编译也报错！
![Uploading 屏幕快照 2013-08-04 下午10.53.45.png . . .]()

**Comment by iAladdin** [comment]
看不到图，
请告知系统版本等信息，谢谢~

错误还是一样么？

**Comment by iAladdin** [comment]
？
