### ISSUE TITLE
Icon尺寸有点大了 跟其他图标放一块显得不太和谐

### ISSUE THREAD

**Issue by Hexor** [iAladdin/Weixin-Mac#4]
![Uploading Screen Shot 2013-10-14 at 8.11.30 PM.png . . .]()

**Comment by Hexor** [comment]
![screen shot 2013-10-14 at 8 26 39 pm](https://f.cloud.github.com/assets/1570783/1325500/f0407420-34cb-11e3-854e-cb55218a2521.png)

会比较挤 = =

**Comment by iAladdin** [comment]
你这是老版本呀。。。你自己编译的？

**Comment by Hexor** [comment]
不是呀 我是到

' 普通用户请到这里 http://ialaddin.github.io/Weixin-Mac/index.html ' 

这里下载的, 觉得普通用户的应该是稳定版 = =

**Comment by iAladdin** [comment]
...那个页面更新没成功。。不知道为啥。。

**Comment by iAladdin** [comment]
又更新了一次。。。

你从这里下载吧~ 

http://yun.baidu.com/share/link?shareid=2891608751&uk=2885731703

**Comment by iAladdin** [comment]
已经更新了该页面了！
嗯。。

**Comment by Hexor** [comment]
嗯 行了
